version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - type: bind
        source: ./docker_rabbitmq/data
        target: /var/lib/rabbitmq
      - type: bind
        source: ./docker_rabbitmq/logs
        target: /var/log/rabbitmq
